import React from "react";

const KycCards: React.FC = () => {
  return (
    <section className="bg-gray-50 py-16 px-4 md:px-8 lg:px-15">
      <div className="max-w-full mx-auto text-center">
        <h2 className="text-3xl md:text-4xl font-bold text-gray-800 mb-12 px-3 sm:px-5 md:px-20">
          <span className="text-[#29a9c5]">SprintVerify's</span> KYC API: The Smart Choice for Your ID Verification Requirements
        </h2>

        <div className="grid gap-10 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 text-left">
          {/* Block 1 */}
          <div className="bg-white p-6 rounded-lg shadow-xl text-center transition duration-300 hover:shadow-2xl">
            <img
              src="/img/11669264_20945843.jpg"
              alt="Personalised Journey"
              className="w-full h-48 object-cover mb-4"
            />
            <h3 className="text-xl font-semibold text-gray-800 mb-2">
              Simplifying Identity Verification
            </h3>
            <p className="text-gray-600">
              Our KYC API is meticulously crafted to streamline the identity verification process for both developers and end-users. With a user-friendly interface and effortless integration, our API ensures that your user's information is accurately verified, providing a seamless user experience.
            </p>
          </div>

          {/* Block 2 */}
          <div className="bg-white p-6 rounded-lg shadow-xl text-center transition duration-300 hover:shadow-2xl">
            <img
              src="/img/8268971_3833777.jpg"
              alt="Trustworthy Efficiency"
              className="w-full h-48 object-cover mb-4"
            />
            <h3 className="text-xl font-semibold text-gray-800 mb-2">
              Combat Fraud with KYC Solution
            </h3>
            <p className="text-gray-600">
              Our KYC Verification process is the ultimate solution for institutions looking to prevent fraudulent activities and fake identities. Leveraging our powerful API, institutions can confidently detect and eliminate any fraudulent attempts, enhancing security measures significantly.
            </p>
          </div>

          {/* Block 3 */}
          <div
            className="bg-white p-6 rounded-lg shadow-xl text-center transition duration-300 hover:shadow-2xl
                          md:col-span-2 md:mx-auto lg:col-span-1 lg:mx-0"
          >
            <img
              src="/img/20289398_6272280.jpg"
              alt="Reliable KYC Verification"
              className="w-full h-48 object-cover mb-4"
            />
            <h3 className="text-xl font-semibold text-gray-800 mb-2">
              Accurate and Reliable KYC Solutions
            </h3>
            <p className="text-gray-600">
              Our Online KYC Check API is designed to verify individuals' identities by cross-referencing their personal information with government records. This rigorous process ensures that the results generated by our solution are accurate, trustworthy, and legally valid, providing peace of mind to institutions and users alike.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default KycCards;
